Controllers/ApplyjobController.cs
using System;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JOBSEARCHPORTAL.Models;

namespace JOBSEARCHPORTAL.Controllers
{
    public class ApplyjobController : Controller
    {
        JobSearchPortalDBEntities1 dbobj = new JobSearchPortalDBEntities1();

        // Action for applying to a job - Load job details
        public ActionResult ApplyCV_Load(int jid)
        {
            // Store job ID in TempData
            TempData["jid"] = jid;

            var job = dbobj.JobTabs.FirstOrDefault(j => j.Job_ID == jid);

            // Pass job details to the view
            ViewBag.JobTitle = job?.Job_Title;
            ViewBag.JobDescription = job?.Job_Description;

            return View();
        }

       
       
        public ActionResult ApplyNow(Application application, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                // Retrieve the job ID from TempData
                int jobId = Convert.ToInt32(TempData["jid"]);

                if (jobId == 0)
                {
                    // Handle case where job ID is not valid
                    ViewData["ErrorMessage"] = "Invalid Job ID";
                    return View("ApplyCV_Load");
                }

                // Save the resume if uploaded
                if (file != null && file.ContentLength > 0)
                {
                    string fileName = Path.GetFileName(file.FileName);
                    var filePath = Server.MapPath("~/Photos");
                    string fullPath = Path.Combine(filePath, fileName);
                    file.SaveAs(fullPath);  // Save the file to the server

                    // Store the file path for the resume
                    application.Resume = Path.Combine("~\\Photos", fileName);
                }

                // Get the user ID from session
                int userId = Convert.ToInt32(Session["usid"]);
                application.uid = userId;

                // Set the job ID
                application.jid = jobId;

                // Set the application date to the current date
                application.ApplicationDate = DateTime.Now;

                // Set the application status
                application.Status = "Applied";

                // Call the stored procedure to insert the application
                dbobj.sp_InsertApplication(application.uid, application.jid, application.ApplicationDate, application.Resume, application.Status);

                // Display success message
                TempData["SuccessMessage"] = "Successfully Applied";
return RedirectToAction("ApplyCV_Load", new { jid = jobId });
            }

            // If validation failed, stay on the current view
            return View("ApplyCV_Load", application);
        }
    }

}

Controllers/JobSearchConController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;
using JOBSEARCHPORTAL.Models;

namespace JOBSEARCHPORTAL.Controllers
{
    public class JobSearchConController : Controller
    {
        JobSearchPortalDBEntities1 dbobj = new JobSearchPortalDBEntities1();

        // GET: JobSearchCon
        public ActionResult JobSearch_Pageload()
        {
            return View(GetData()); // Show all jobs when the page first loads
        }

        // Fetch all job data
        private JobSearchClass GetData()
        {
            var joblist = new JobSearchClass();
            List<string> lst = new List<string>();

            var jobs = dbobj.JobTabs.ToList();

            foreach (var e in jobs)
            {
                var jobcls = new Jobsearch();

                jobcls.JobId = e.Job_ID;
                jobcls.CompanyId = e.Company_ID;
                jobcls.JobTitle = e.Job_Title;
                jobcls.JobDescription = e.Job_Description;
                jobcls.JobSkills = e.Job_Skills;
                jobcls.JobExperience = e.Job_Experience;
                jobcls.JobType = e.Job_Type;
                jobcls.JobWorkMode = e.Job_WorkMode;
                jobcls.JobLocation = e.Job_Location;
                jobcls.JobSalaryRange = e.Job_SalaryRange;
                jobcls.JobEndDate = e.Job_EndDate;
                jobcls.JobStatus = e.Job_Status;

                joblist.selectjob.Add(jobcls);

                var s = jobcls.JobSkills;
                lst.Add(s);
            }

            TempData["ski"] = string.Join(" ", lst);
            return joblist;
        }




        // Handle the search functionality
        public ActionResult searchjob_click(JobSearchClass clsobj)
        {
            string qry = " ";

            // Add filters dynamically based on user input
            if (!string.IsNullOrWhiteSpace(clsobj.insertse.JobSkills))
                qry += " AND Job_Skills LIKE '%" + clsobj.insertse.JobSkills + "%'";
            if (!string.IsNullOrWhiteSpace(clsobj.insertse.JobExperience))
                qry += " AND Job_Experience LIKE '%" + clsobj.insertse.JobExperience + "%'";
            if (!string.IsNullOrWhiteSpace(clsobj.insertse.JobLocation))
                qry += " AND Job_Location LIKE '%" + clsobj.insertse.JobLocation + "%'";

            // Call the stored procedure to get the filtered data
            return View("JobSearch_Pageload", GetData1(clsobj,qry));
        }

        // Fetch filtered job data based on the query using stored procedure
        private JobSearchClass GetData1(JobSearchClass clsobj, string qry)
        {
            using (var con = new SqlConnection(ConfigurationManager.ConnectionStrings["newconnection"].ConnectionString))
            {
                SqlCommand cmd = new SqlCommand("sp_jobsearches", con);
                cmd.CommandType = CommandType.StoredProcedure;

                cmd.Parameters.AddWithValue("@qry", qry);
                con.Open();
                SqlDataReader dr = cmd.ExecuteReader();

                var joblist = new JobSearchClass();

                while (dr.Read())
                {
                    var jobcls = new Jobsearch();
                    jobcls.JobId = Convert.ToInt32(dr["Job_ID"]);
                    jobcls.CompanyId = Convert.ToInt32(dr["Company_ID"]);
                    jobcls.JobTitle = dr["Job_Title"].ToString();
                    jobcls.JobDescription = dr["Job_Description"].ToString();
                    jobcls.JobSkills = dr["Job_Skills"].ToString();
                    jobcls.JobExperience = dr["Job_Experience"].ToString();
                    jobcls.JobType = dr["Job_Type"].ToString();
                    jobcls.JobWorkMode = dr["Job_WorkMode"].ToString();
                    jobcls.JobLocation = dr["Job_Location"].ToString();
                    jobcls.JobSalaryRange = dr["Job_SalaryRange"].ToString();
                    jobcls.JobEndDate = Convert.ToDateTime(dr["Job_EndDate"]);
                    jobcls.JobStatus = dr["Job_Status"].ToString();


                    joblist.selectjob.Add(jobcls);  // Add the job to the list
                }
                con.Close();
                return joblist;  // Return the populated job list
            }
        }




    }
}

Controllers/LoginController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using JOBSEARCHPORTAL.Models;

namespace JOBSEARCHPORTAL.Controllers
{
    public class LoginController : Controller
    {
        JobSearchPortalDBEntities1 dbobj = new JobSearchPortalDBEntities1();

        // GET: Login
        public ActionResult Login_pageload()
        {
            return View();
        }

        public ActionResult UserHome()
        {
            return View();
        }

        public ActionResult AdminHome()
        {
            return View();
        }

        // POST: Handle Login

        public ActionResult Login_click(Loginclass clsobj)
        {
            var val = dbobj.sp_loginCountId(clsobj.uname, clsobj.pswd).Single();
            if (val == 1)
            {
                var uid = dbobj.sp_loginId(clsobj.uname, clsobj.pswd).FirstOrDefault();
                Session["usid"] = uid;
                var lt = dbobj.sp_logtype(clsobj.uname, clsobj.pswd).FirstOrDefault();
                if (lt == "User")
                {
                    return RedirectToAction("UserHome");
                }
                else if (lt == "Company")
                {
                    return RedirectToAction("AdminHome");
                }
            }
            else
            {
                ModelState.Clear();
                clsobj.msg = "Invalid Login";
                return View("Login_pageload", clsobj);
            }
            return View("Login_pageload", clsobj);
        }

    }

}

Views/JobSearchCon/JobSearch_Pageload.cshtml
@model JOBSEARCHPORTAL.Models.JobSearchClass

@{
    ViewBag.Title = "Job Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Job Search</h1>

<div>
    @using (Html.BeginForm("searchjob_click", "JobSearchCon", FormMethod.Post))
    {
        <table>
            <tr>
                <td><label>Skills:</label></td>
                <td>@Html.TextBoxFor(m => m.insertse.JobSkills, new { @class = "form-control", placeholder = "Enter Skills" })</td>
                <td><label>Experience:</label></td>
                <td>@Html.TextBoxFor(m => m.insertse.JobExperience, new { @class = "form-control", placeholder = "Enter Experience" })</td>
                <td><label>Location:</label></td>
                <td>@Html.TextBoxFor(m => m.insertse.JobLocation, new { @class = "form-control", placeholder = "Enter Location" })</td>
            </tr>
            <tr>
                <td><input type="submit" value="Search" class="btn btn-primary" /></td>
            </tr>
        </table>
    }
</div>

<div>
    @using (Html.BeginForm("JobSearch_Pageload", "JobSearchCon", FormMethod.Get))
    {
        if (Model != null)
        {
            if (Model.selectjob != null && Model.selectjob.Count != 0)
            {
        <table class="table table-bordered">
            <tr></tr>
                <tr>
                    <th>Company ID</th>
                    <th>Job Title</th>
                    <th>Skills</th>
                    <th>Experience</th>
                    <th>Location</th>
                    <th>Salary Range</th>
                    <th>End Date</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
           
           
                @foreach (var item in Model.selectjob)
                {
                    <tr>
                        <td>@item.CompanyId</td>
                        <td>@item.JobTitle</td>
                        <td>@item.JobSkills</td>
                        <td>@item.JobExperience</td>
                        <td>@item.JobLocation</td>
                        <td>@item.JobSalaryRange</td>
                        <td>@item.JobEndDate.ToString("yyyy-MM-dd")</td>
                        <td>@item.JobStatus</td>
                        <td>
                            @Html.ActionLink("Apply Now", "ApplyCV_Load", "Applyjob",
                          new { jid = item.JobId }, null)
                        </td>
                    </tr>
                }
            
        </table>
            }
            else
            {
    <script>
        alert(' No data found ');
    </script>
            }
        }
    }



<div style="margin-top: 20px;">
    @Html.ActionLink("Back to Home Page", "UserHome", "Login")
</div>
</div>