Controllers/JobaddController.cs
using System;
using System.Web.Mvc;
using JOBSEARCHPORTAL.Models;

namespace JOBSEARCHPORTAL.Controllers
{
    public class JobAddController : Controller
    {
        JobSearchPortalDBEntities1 dbobj = new JobSearchPortalDBEntities1();

        // GET: Admin Home
        public ActionResult AdminHome()
        {
            return View();
        }

        // POST: Insert Job
        public ActionResult InsertJob_Click(Jobclass clsobj)
        {

            if (ModelState.IsValid)
            {
                int CompId = Convert.ToInt32(Session["usid"]);
                clsobj.cid = CompId;

                dbobj.sp_InsertJob(clsobj.cid, clsobj.JobTitle, clsobj.JobDescription, clsobj.JobSkills, clsobj.JobExperience, clsobj.JobType, clsobj.JobWorkMode, clsobj.JobLocation, clsobj.JobSalaryRange, clsobj.JobEndDate, clsobj.JobStatus);
                clsobj.Msg = "Successfully Inserted";
                return RedirectToAction("AdminHome", "Login");
            }
            return RedirectToAction("AdminHome", clsobj);
        }
    }
    

    
}

 

Views/Jobadd/AdminHome.cshtml
@model JOBSEARCHPORTAL.Models.Jobclass
@{
    ViewBag.Title = "AdminHome";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Company Vaccancy</h2>


<div>
    @using (Html.BeginForm("InsertJob_Click", "JobAdd", FormMethod.Post))
    {
        <div>
            <label>Job Title:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.JobTitle)
            @Html.ValidationMessageFor(m => m.JobTitle)
        </div>

        <div>
            <label>Job Description:</label>
        </div>
        <div>
            @Html.TextAreaFor(m => m.JobDescription)
            @Html.ValidationMessageFor(m => m.JobDescription)
        </div>

        <div>
            <label>Job Skills:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.JobSkills)
            @Html.ValidationMessageFor(m => m.JobSkills)
        </div>

        <div>
            <label>Job Experience:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.JobExperience)
            @Html.ValidationMessageFor(m => m.JobExperience)
        </div>

        <div>
            <label>Job Type:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.JobType)
            @Html.ValidationMessageFor(m => m.JobType)
        </div>

        <div>
            <label>Work Mode:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.JobWorkMode)
            @Html.ValidationMessageFor(m => m.JobWorkMode)
        </div>

        <div>
            <label>Location:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.JobLocation)
            @Html.ValidationMessageFor(m => m.JobLocation)
        </div>

        <div>
            <label>Salary Range:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.JobSalaryRange)
            @Html.ValidationMessageFor(m => m.JobSalaryRange)
        </div>

        <div>
            <label>End Date:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.JobEndDate, new { type = "date" })
            @Html.ValidationMessageFor(m => m.JobEndDate)
        </div>

        <!-- Hidden field for Job Status -->
        @Html.HiddenFor(m => m.JobStatus, new { Value = "Open" })

        <div>
            <input type="submit" value="Add Job" />
            @Html.DisplayFor(m => m.Msg)
        </div>
    }

    <div style="margin-top: 20px;">
        @Html.ActionLink("Back to Home Page", "AdminHome", "Login")
    </div>
</div>

Views/Jobadd/InsertJob_Pageload.cshtml
@model JOBSEARCHPORTAL.Models.Jobclass
@{
    ViewBag.Title = "InsertJob_Pageload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add Job</h2>

@using (Html.BeginForm("InsertJob_Click", "Jobadd", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div>
        <label>Job Title:</label>
        @Html.TextBoxFor(m => m.JobTitle)
        @Html.ValidationMessageFor(m => m.JobTitle)
    </div>

    <div>
        <label>Job Description:</label>
        @Html.TextBoxFor(m => m.JobDescription)
        @Html.ValidationMessageFor(m => m.JobDescription)
    </div>

    <div>
        <label>Job Skills:</label>
        @Html.TextBoxFor(m => m.JobSkills)
        @Html.ValidationMessageFor(m => m.JobSkills)
    </div>

    <div>
        <label>Job Experience:</label>
        @Html.TextBoxFor(m => m.JobExperience)
        @Html.ValidationMessageFor(m => m.JobExperience)
    </div>

    <div>
        <label>Job Type:</label>
        @Html.TextBoxFor(m => m.JobType)
        @Html.ValidationMessageFor(m => m.JobType)
    </div>

    <div>
        <label>Job Work Mode:</label>
        @Html.TextBoxFor(m => m.JobWorkMode)
        @Html.ValidationMessageFor(m => m.JobWorkMode)
    </div>

    <div>
        <label>Job Location:</label>
        @Html.TextBoxFor(m => m.JobLocation)
        @Html.ValidationMessageFor(m => m.JobLocation)
    </div>

    <div>
        <label>Job Salary Range:</label>
        @Html.TextBoxFor(m => m.JobSalaryRange)
        @Html.ValidationMessageFor(m => m.JobSalaryRange)
    </div>

    <div>
        <label>Job End Date:</label>
        @Html.TextBoxFor(m => m.JobEndDate, new { type = "date" })
        @Html.ValidationMessageFor(m => m.JobEndDate)
    </div>

    <div>
        <label>Job Status:</label>
        @Html.TextBoxFor(m => m.JobStatus)
        @Html.ValidationMessageFor(m => m.JobStatus)
    </div>

    <div>
        <input type="submit" value="Add Job" />
    </div>

    <div>
        @Html.DisplayFor(m => m.Msg)
    </div>
}